export const UPDATE_MEMBERS_LIST = 'UPDATE_MEMBERS_LIST'
export const SET_ROOM_NAME = 'SET_ROOM_NAME'
export const SET_ROOM_ID = 'SET_ROOM_ID'
export const SET_ROOM_DIF = 'SET_ROOM_DIF'
export const UPDATE_ROOM_MESSAGE = 'UPDATE_ROOM_MESSAGE'

