export const CHANGE_JIGSAW_PIC_TO_JIG = 'CHANGE_JIGSAW_PIC_TO_JIG';
export const CHANGE_JIGSAW_JIG_TO_JIG = 'CHANGE_JIGSAW_JIG_TO_JIG';
export const CHANGE_JIGSAW_JIG_TO_PIC = 'CHANGE_JIGSAW_JIG_TO_PIC';
export const SET_CHANGE = 'SET_CHANGE';
export const SET_SCORE = 'SET_SCORE';
export const UPDATE_JIGSAW_DATA = 'UPDATE_JIGSAW_DATA';